# Generated by Django 3.2.5 on 2021-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='author',
        ),
    ]
