# Generated by Django 3.2.5 on 2021-07-23 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210722_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(),
        ),
    ]
