# Generated by Django 3.2.7 on 2021-10-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='09/30', max_length=100),
        ),
    ]
