# Generated by Django 4.0.4 on 2022-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='06/26', max_length=100),
        ),
    ]
